### ISSUE TITLE
한국어 lang 속성에 keep-all 추가

### ISSUE THREAD

**Issue by hannah26hannah** [dun-land/consumer59#1]
간단하게 수정하고 PR 올리려고 하는데, Permission이 없어서 이슈로 대체합니다! 

SPC 이슈에 관심이 많은데, 종종 기여/이슈 남기러 오겠습니다 👍

**Comment by dungsil** [comment]
감사합니다 ! 수정해서 반영했습니다 👍 
PR 권한이 없다니 혹시 fork 가 안되시는걸까요? 🤔🤔

**Comment by hannah26hannah** [comment]
오 아닙니다 ! 제가 착각했었어요 ㅎㅎ fork 잘 됩니다 ! 👍
